/**
 * Formato de salida serializado para los registros generados por el CLI.
 *
 * Serialized output format for the records generated by the CLI.
 */
export type OutputFormat = 'json' | 'csv' | 'ndjson';

/**
 * Un registro generado por un subcomando, listo para serializar.
 *
 * A record generated by a subcommand, ready to be serialized.
 */
export type Row = Record<string, string | number>;

/**
 * Abstracción de entrada/salida usada por el CLI, para poder capturar
 * stdout/stderr en tests sin tocar los streams reales del proceso.
 *
 * Input/output abstraction used by the CLI, so tests can capture
 * stdout/stderr without touching the process's real streams.
 */
export interface Io {
  /** Escribe una porción de texto a stdout. / Writes a chunk of text to stdout. */
  stdout: (chunk: string) => void;
  /** Escribe una porción de texto a stderr. / Writes a chunk of text to stderr. */
  stderr: (chunk: string) => void;
}

/**
 * Opciones comunes a todos los subcomandos del CLI.
 *
 * Options common to all CLI subcommands.
 */
export interface CommonOptions {
  /** Seed determinística (entero o texto). / Deterministic seed (integer or text). */
  seed: number | string;
  /** Cantidad de registros a generar. / Number of records to generate. */
  count: number;
  /** Formato de salida serializado. / Serialized output format. */
  format: OutputFormat;
}
